{% set version = "2.1.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rcppthread
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppThread_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppThread/RcppThread_{{ version }}.tar.gz
  sha256: 88debafefb13a77e507eeb2ae2a9e53f717e8cff071fcb4063b2be549423bbe8

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('RcppThread')"           # [not win]
    - "\"%R%\" -e \"library('RcppThread')\""  # [win]

about:
  home: https://github.com/tnagler/RcppThread
  license: MIT
  summary: Provides a C++11-style thread class and thread pool that can safely be interrupted from R.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: RcppThread
# Title: R-Friendly Threading in C++
# Version: 0.5.4
# Authors@R: person("Thomas", "Nagler", email = "mail@tnagler.com", role = c("aut", "cre"))
# Description: Provides a C++11-style thread class and thread pool that can safely be interrupted from R.
# Depends: R (>= 3.3.0)
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# SystemRequirements: C++11
# URL: https://github.com/tnagler/RcppThread
# BugReports: https://github.com/tnagler/RcppThread/issues
# RoxygenNote: 6.1.1
# Suggests: testthat, R.rsp, Rcpp
# VignetteBuilder: R.rsp
# NeedsCompilation: no
# Packaged: 2019-10-18 22:03:00 UTC; n5
# Author: Thomas Nagler [aut, cre]
# Maintainer: Thomas Nagler <mail@tnagler.com>
# Repository: CRAN
# Date/Publication: 2019-10-19 05:20:15 UTC
